"""
import_dry_4.py — lihat catatan di import_printing_2.py (versi Excel-di-Drive).
"""

from import_engine import run_excel_import

SOURCE_KEY = "dry_4"
TARGET_SHEET_NAME = "DRY_4"

TARGET_HEADERS = [
    "TANGGAL", "SHIFT/OPERATOR", "JAM_AWAL", "JAM_AKHIR", "SPK", "JO", "NAMA_PRODUK",
    "LAP1/LAP2", "HPREW_NO_BAHAN", "HPREW_NO", "HPREW_METER", "HPREW_KG", "HPREW_JAM_NAIK",
    "LAPISAN_JENIS", "LAPISAN_MIC", "LAPISAN_UKURAN", "LAPISAN_METER", "LAPISAN_KG", "LAPISAN_NO_BAHAN",
    "HASIL_PRODUKSI_NO", "HASIL_PRODUKSI_METER", "HASIL_PRODUKSI_KG", "HASIL_PRODUKSI_JAM_TURUN",
    "HASIL_PRODUKSI_WIP", "HASIL_PRODUKSI_BARIS", "AGING_ROOM", "WASTE", "KETERANGAN_WASTE"
]

HEADER_KEYWORDS = ["TANGGAL", "SHIFT/OPERATOR", "JO", "SPK"]

if __name__ == "__main__":
    run_excel_import(SOURCE_KEY, TARGET_SHEET_NAME, TARGET_HEADERS, HEADER_KEYWORDS)
